name: Build and publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'docker/**'
      - '.dockerignore'
      - '.github/workflows/publish-image.yml'
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: build image
        run: |
          docker build --file docker/Dockerfile --tag slimjimserver/recommendarr:latest .
      - name: push image to docker hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username slimjimserver --password-stdin
          docker push slimjimserver/recommendarr:latest
