name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'docker/Dockerfile'
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./docker/ -t slimjimserver/recommendarr:latest
      - name: push image to docker hub
        run: |
          docker login -u slimjimserver -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push slimjimserver/recommendarr:latest